title: Felix Cenusa
email: felixcenusa@gmail.com
description: >- 
  Currently just redirects to other websites i have with github pages.
baseurl: "" 
mebig: /assets/img/meBig.png
show_downloads: false
theme: jekyll-theme-hacker